title:              Andrey Filatov
email:              filatovandreiv@gmail.com
description:        Personal page
author:             Andrey Filatov
baseurl:            "/"
url:                "https://anvilarth.github.io"

# Social Profiles
twitter_username:   anvilapex
github_username:    anvilarth
facebook_username:  
instagram_username:  
linkedin_username: andrey-filatov

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
mathjax:            true
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate